Pull up following revision(s) (requested by khorben in ticket #1730):
	build.sh: revision 1.374

build.sh: add support for git worktree

Git supports multiple working trees attached to the same repository,
with the git-worktree(1) subcommand.

When building from a Git working tree, the repository metadata in .git
from the top source directory is a file (containing the actual location
of the metadata) instead of the usual directory structure. With this
change, build.sh allows .git to be a directory or a regular file
instead, therefore letting the sources build as expected from a Git
working tree.

To test: (without this patch)
   src$ git worktree add ../src-clean-tree
   [...]
   src$ (cd ../src-clean-tree && ./build.sh tools)
   [...]
   ERROR: Cannot determine VCS for '.../src-clean-tree/'