mount_lfs(8): Add unreachable() to fix clang build.
dependall ===> sbin/mount_lfs
/home/source/ab/HEAD-llvm/src/sbin/mount_lfs/mount_lfs.c:319:1: error: function declared 'noreturn' should not return [-Werror,-Winvalid-noreturn]

The only two cases in invoke_cleaner are already handled, so the rest
should be unreachable.