Set provider to NULL -- "pam" is not a valid security key helper library. Now ssh-agent no longer fails key addition with
    error: Cannot add provider: RSA is not an authenticator-hosted key