Linker semantics have changed; we now don't automatically link dependent libraries from other DSO's. For example in /usr/bin/passwd: ld: krb5_passwd.o: undefined reference to symbol \ 	'UI_UTIL_read_pw_string@@OPENSSL_1_1_0' ld: /usr/obj/amd64-x86_64/release/lib/libcrypto.so.14: error adding symbols: \ 	DSO missing from command line